#端口号
server:
  port: 8082
  servlet:
    encoding: #中文乱码
      charset: UTF-8
      force: true
      enabled: true

#服务名
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 536870912
      max-request-size: 536870912 #512Mb
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
##ali -vod
aliyun:
  vod:
    file:
      accessKeyId: LTAI5t7ugyR19pL2TWDM2BCG
      accessKeySecret: ZrcpgbFQzPGuDddsvURLTitqdkrgju
      cateId: 1000378385 #分类节点ID
