#端口号
server:
  port: 8084
  servlet:
    encoding: #中文乱码
      charset: UTF-8
      force: true
      enabled: true

#服务名
spring:
  application:
    name: service-msm
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  mail: #邮箱配置
    host: smtp.163.com
    port:
    username: gffffxcb@163.com
    password: SAXUCUMATAGCSFCT
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  redis:
    host: 124.222.55.226
    port: 6333
    database: 0
    password: root123
    timeout: 8000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 1
#ali -msm
aliyun:
  vod:
    file:
      accessKeyId: LTAI5t7ugyR19pL2TWDM2BCG
      accessKeySecret: ZrcpgbFQzPGuDddsvURLTitqdkrgju
