#端口号
server:
  port: 8085
  servlet:
    encoding: #中文乱码
      charset: UTF-8
      force: true
      enabled: true

#服务名
spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://rm-bp1lcm693d2fe6730po.mysql.rds.aliyuncs.com/edu_online?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XHY123456m
    hikari: #添加池并发数量避免链接失败
      maximum-pool-size: 10
      connection-timeout: 60000
      max-lifetime: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      minimum-idle: 10
      login-timeout: 5
  jackson: #日期解析器
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos: #nacos配置
      server-addr: 127.0.0.1:8848  #服务地址
    sentinel:
      transport:
        port: 8719 #如果被占用会增加1
        dashboard: 127.0.0.1:8080 #sentineldashboard地址
  redis:
    host: 124.222.55.226
    port: 6333
    database: 0
    password: root123
    timeout: 8000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 1
#mybatis-plus 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#扫描mapper文件
mapper-locations: classpath:com/mgh/order/mapper/*.xml

feign: #服务发现调用
  client:
    config:
      default:
        connectTimeout: 60000  #nacos服务调用超时时间
        readTimeout: 60000
  sentinel:
    enabled: true #开启在feign服务调用中的sentinel熔断处理功能

