#端口号
server:
  port: 8081
  servlet:
    encoding: #中文乱码
      charset: UTF-8
      force: true
      enabled: true

#服务名
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880 #5m
#ali -oss
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: LTAI5t7ugyR19pL2TWDM2BCG
      accessKeySecret: ZrcpgbFQzPGuDddsvURLTitqdkrgju
      bucketName: edu-online-manager
